# Dependencies
markdown:         kramdown
rouge:            pygments

# Permalinks
permalink:        pretty
gem:              [jekyll-paginate, jekyll-gists]
# Setup
title:            상 한규 / Hangyu Sang
tagline:          ''
description:      'Little Waterdrops make Blue Whale'
url:              'http://littlewaterdrops.github.io'
baseurl:          /

author:
  name:           'Hangyu Sang'
  url:            'https://littlewaterdrops.github.io'

paginate:         5

# Custom vars
version:          2.1.0

github:           'https://github.com/LittleWaterDrops?tab=repositories'
  repo:           'https://github.com/LittleWaterDrops?tab=repositories'