# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
gem: [jekyll-paginate, jekyll-gists]
# Setup
title:            상 한규 / Hangyu Sang
tagline:          'A Jekyll theme'
description:      'Little water drops make Blue Whale'
url:              'http://littlewaterdrops.github.io'
baseurl:          ''

author:
  name:           'Hangyu Sang'
  url:            'https://littlewaterdrops.github.io'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           