title: 상 한규 / Hangyu Sang
description: >-
  Little Waterdrops make Blue Whale
url: "https://littlewaterdrops.github.io"
github: LittleWaterDrops
email: nic6@naver.com
google_analytics: UA-146771648-1

exclude: [README.md, Gemfile, Gemfile.lock]

comment:
  enabled: true
  repo: LittleWaterDrops/littlewaterdrops.github.io-comments
  issue-term: pathname
  theme: github-light

collections:
  pages:
    output: true
  projects:
    output: true
  tags:
    output: true

defaults:
  - scope:
      type: pages
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
      permalink: /blog/:title
  - scope:
      type: projects
    values:
      layout: project
      permalink: /projects/:title
  - scope:
      type: tags
    values:
      layout: tag
      permalink: /tags/:title
